---
- hosts: all
  tasks:
    - name: hour
      shell: echo "{{ var1 }}" > schedules && cat schedules
      register: hour
      
    - name: day
      shell: echo "{{ var2 }}" > days && cat days
      register: day

    - name: hour
      debug:
        var: hour.stdout
    - name: day
      debug:
        var: day.stdout
