---
- hosts: all
  tasks:
    - name: Consulta dados
      command: sh /home/matheus/consulta_dados.sh
      register: data
    
    - name: Consulta Banco
      command: sh /home/matheus/busca_banco.sh
      register: data_banco
      
    - name: dados
      debug: 
        var: data.stdout

    - name: banco
      debug: 
        var: data_banco.stdout
