---
- hosts: all
  tasks:
    - name: Consulta Numero Terminal
      debug:
        msg: "{{ lookup('file', 'teste') }}"
    
    - name: Consulta IP Terminal
      debug:
        msg: "{{ lookup('file', 'teste2') }}"
          
