---
- hosts: all
  tasks:
    - name: Consulta Numero Terminal
      set_fact:
        terminal_number: "12345"
        ip: "172.26.226.230"
        room_name: "PAE SNC CONGRESSO"
        simtc: "false"
        accessibility: "false"
        auxilio_emergencial: "false"
        fgts_card: "true"
        fgts: "true"
        

    - name: Message
      debug:
        msg: >-
             SIGML_OUTPUT { "terminal_number": { "value": {{ terminal_number }}, "type": "number", "label": "Número do Terminal"}
             } SIGML_OUTPUT
          
