---
- hosts: all
  tasks:
    - name: Consulta dados
      command: sh /home/consulta_dados.sh
      register: data
    
    - name: Consulta Banco
      command: sh /home/busca_banco.sh
      register: data_banco
      
    - name: dados
      debug: 
        var: data.stdout
    
    - name: Consulta Numero Terminal
      vars: 
        contents: "{{ lookup('file', 'teste') }}"
      tasks:
        debug:
          msg: "{{ contents }}"
    
    - name: Consulta IP Terminal
      vars: 
        ip: "{{ lookup('file', 'teste2') }}"
      tasks:
        debug:
          msg: "{{ ip }}"
          

    - name: banco
      debug: 
        var: data_banco.stdout
