---
- hosts: all
  tasks:
    - name: Consulta Numero Terminal
      debug:
        msg: "{{ lookup('file', '/tmp/teste.txt') }}"
    
    - name: Consulta IP Terminal
      debug:
        msg: "{{ lookup('file', '/tmp/teste2.txt') }}"
          
