---
- hosts: all
  tasks: 
    - name: Busca texto
      shell: grep -A 50000 -a '2022-06-22 11:30:18' /home/matheus/test.log |grep -ao 'Estado Manutencao{{':'}} MANUTENCAO_REOMOTA'
      args:
        executable: /bin/bash
        warn: false
      register: result
      ignore_errors: yes
    - debug:
        msg: {{ result.stdout }}
