---
- hosts: all
  tasks:
    - name: hostname-teste
      shell: hostname
      register: hostname

    - name: ip
      shell: hostname -I
      register: ip

    - name: error
      shell: echo 'ASD'
      register: error
      ignore_errors: true
    
    - name: print hostname
      debug: 
        var: hostname.stdout_lines
        verbosity: 4

    - name: print ip
      debug: 
        msg: "SIGML_OUTPUT {{ip.stdout_lines}} SIGML_OUTPUT"
        verbosity: 2
    
    - name: print error
      debug: 
        msg: error.stdout_lines
