---
- hosts: all
  tasks:
    - name: hostname
      shell: hostname
      register: hostname

    - name: ip
      shell: hostname -I
      register: ip

    - name: error
      shell: cat asd
      register: error

    - debug: 
        var: hostname.stdout_lines
        verbosity: 4
    - debug: var="SIGML_OUTPUT {{ip.stdout_lines}} SIGML_OUTPUT"
    - debug: var=error.stdout_lines
