
---
- hosts: all
  tasks:
  
    - name: Sinaliza Manutenção
      command: echo 'ALTERA O BANCO'

    - name: Retry a task until a certain condition is met
      command: tail -n 20 /home/matheus/test.log
      register: result
      until: result.stdout.find("MANUTENCAO_LIBERADA") != -1
      retries: 20
      delay: 2
      ignore_errors: yes
      
    - name: Executa manutenção
      command: echo 'EXECUTANDO MANUTENÇÃO'
      when: result is succeeded
    
    - name: Reboot
      command: shutdown -r +1
      async: 1
      poll: 0
      when: result is succeeded
    
#     - debug:
#         msg: "TERMINAL EM MANUTENÇÃO"
#       when: result is succeeded
    
#     - debug:
#         msg: "TERMINAL EM USO"
#       when: result is failed
