
---
- hosts: all
  tasks:
  
    - name: Sinaliza Manutenção
      command: echo 'ALTERA O BANCO'
    
    - name: Pegar horario
      shell: date '+%Y-%m-%d %H:%M'
      args:
        warn: false
      register: hr_local

    - name: Verificando Liberação da Aplicação
      shell: grep -A 50000 -a "{{ hr_local.stdout }}" /home/matheus/test.log | grep -a "MANUTENCAO_LIBERADA"
      register: result
      until: result.stdout.find("MANUTENCAO_LIBERADA") != -1
      retries: 20
      delay: 2
      ignore_errors: yes
      
    - name: Executa manutenção
      command: echo 'EXECUTANDO MANUTENÇÃO'
      when: result is succeeded
    
    - name: Reboot
      command: reboot
      async: 5
      poll: 0
      when: result is succeeded
    
#     - debug:
#         msg: "TERMINAL EM MANUTENÇÃO"
#       when: result is succeeded
    
#     - debug:
#         msg: "TERMINAL EM USO"
#       when: result is failed
