
---
- hosts: all
  tasks:
    - name: Retry a task until a certain condition is met
      command: tail -n 1 /home/matheus/test.log
      register: result
      until: result.stdout.find("Terminal em uso") != -1
      retries: 20
      delay: 5
      
    - debug:
        msg: "TERMINAL EM MANUTENÇÃO"
