---
- hosts: all
  gather_facts: no
  tasks:
    - name: Lendo arquivo
      command: "tail -n1 {{ item }}"
      loop:
        -  /home/matheus/test.log
        -  /home/matheus/test.log
        -  /home/matheus/test.log
        -  /home/matheus/test.log
        -  /home/matheus/test.log
      loop_control:
        pause: 2
      register: result
      async: 50
      poll: 0
    
    - name: Wait for asynchronous job to end
      async_status:
        jid: '{{ result_item.ansible_job_id }}'
      loop: "{{ result.results }}"
      loop_control:
        loop_var: "result_item"
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 1

    - debug:
        msg: "RESULT_OBJ {{ result }} "
        
    
    - debug:
        msg: "JOB_RESULT_OBJ {{ job_result }} "

    - debug:
        msg: "TERMINAL EM MANUTENÇÃO"
      when: result is succeeded
    
    - debug:
        msg: "TERMINAL EM USO"
      when: result is failed
