---
- hosts: all
  gather_facts: no
  tasks:
    - name: Retry a task until a certain condition is met
      command: tail -n 1 /home/matheus/test.log
      register: result
      #until: result.stdout.find("Terminal livre") != -1
      #retries: 20
      #delay: 2
      ignore_errors: yes
      async: 50
      pool: 0

    - debug:
        msg: "Conteudo do arquivo: {{ result.stdout }} "
      until: result.fineshed
      retries: 20
      delay: 2
      
    
    - debug:
        msg: "TERMINAL EM MANUTENÇÃO"
      when: result is succeeded
    
    - debug:
        msg: "TERMINAL EM USO"
      when: result is failed
