---
- hosts: all
  gather_facts: no
  tasks:
    - name: Lendo arquivo
      command: "tail -n1 {{ item }}"
      loop:
        -  /home/matheus/test.log
        -  /home/matheus/test.log
        -  /home/matheus/test.log
        -  /home/matheus/test.log
        -  /home/matheus/test.log
      loop_control:
        pause: 2
      register: result
      async: 50
      poll: 0
      
    - debug:
        msg: "RESULT_OBJ {{ result }} "

    - debug:
        msg: "TERMINAL EM MANUTENÇÃO"
      when: result is succeeded
    
    - debug:
        msg: "TERMINAL EM USO"
      when: result is failed
